### PR TITLE
Step2 program logic

### PR DESCRIPTION
**Pull request by bitPogo**
Review this step before the model/schema and after the validators

### CODE REVIEW

**Comment by manicki** [comment]
Needs a manual rebase now. Will see if I'll be able to do it.

**Comment by bitPogo** [comment]
I'll do the rebase

**Comment by manicki** [comment]
the rebase apparently didn't go entirely OK, as commits are duplicated. Will adjust.

**Comment by manicki** [comment]
Re-submitted as https://github.com/wmde/wikibase-docker-yml-gui/pull/20

**Pull request closed without merging**
